name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-server .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python-server'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name test-server python-server
          sleep 3

      - name: Test server response
        run: |
          response=$(curl -s http://localhost:8080)
          echo "$response"
          echo "Server response: $response"
          echo "$response" | grep '"message":' | grep '"Hello Server Python"'
          echo "$response" | grep '"status":' | grep '"success"'

      - name: Stop container
        run: | 
          docker stop test-server
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
     - name: Deploy
       run: echo "Realizando deploy da aplicação..."
